/*
 * Generates native/packed_tables.h from the original PULCHRA data headers.
 *
 * Every coordinate in the three statistical tables has exactly three decimals
 * and lies within +-8 A, so it is stored as an int16 in milli-Angstrom; the
 * small integer columns are stored as int8; the offset column of
 * rot_stat_idx is a running sum that pulchra_data.c recomputes at start-up.
 * Sentinel rows (-1 markers) are kept verbatim.  verify_tables.c checks that
 * the decoded tables are bit-identical to the originals.
 *
 *   cc -O1 -I.. -o pack_tables pack_tables.c && ./pack_tables > ../packed_tables.h
 */
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <stdint.h>

typedef struct { int bins[3]; float data[8][3]; } nco_struct;
#include "../nco_data.h"
#include "../rot_data_coords.h"
#include "../rot_data_idx.h"

static const int nheavy[20] = {0, 1, 2, 2, 3, 3, 4, 3, 4, 4, 4, 4, 5, 5, 5, 7, 6, 7, 8, 10};

static int16_t q(float v, const char *what, long where) {
  double m = v * 1000.0, r = round(m);
  if (fabs(m - r) > 1e-3 || fabs(r) > 32767) {
    fprintf(stderr, "%s[%ld] = %.9g is not a 3-decimal value in int16 range\n", what, where, v);
    exit(1);
  }
  return (int16_t)r;
}

static void emit_nco(const char *name, const nco_struct *t, size_t n) {
  size_t i; int j, k;
  printf("#define %s_N %zu\nstatic const int8_t %s_bins[%zu][3] = {\n", name, n, name, n);
  for (i = 0; i < n; i++) {
    for (k = 0; k < 3; k++) if (t[i].bins[k] < -128 || t[i].bins[k] > 127) { fprintf(stderr, "bin out of int8\n"); exit(1); }
    printf("{%d,%d,%d},%s", t[i].bins[0], t[i].bins[1], t[i].bins[2], (i % 8 == 7) ? "\n" : "");
  }
  printf("};\nstatic const int16_t %s_data[%zu][24] = {\n", name, n);
  for (i = 0; i < n; i++) {
    printf("{");
    for (j = 0; j < 8; j++) for (k = 0; k < 3; k++) printf("%d,", q(t[i].data[j][k], name, (long)i));
    printf("},\n");
  }
  printf("};\n");
}

int main(void) {
  size_t n_nco = sizeof(nco_stat) / sizeof(nco_stat[0]);
  size_t n_pro = sizeof(nco_stat_pro) / sizeof(nco_stat_pro[0]);
  size_t n_coord = sizeof(rot_stat_coords) / sizeof(rot_stat_coords[0]);
  size_t n_idx = sizeof(rot_stat_idx) / sizeof(rot_stat_idx[0]);
  size_t i; int k; long off = 0;

  printf("/* GENERATED by native/tools/pack_tables.c from nco_data.h, rot_data_coords.h,\n"
         "   rot_data_idx.h -- do not edit.  Decoded at start-up by pulchra_data.c. */\n");
  emit_nco("PK_NCO", nco_stat, n_nco);
  emit_nco("PK_NCO_PRO", nco_stat_pro, n_pro);

  printf("#define PK_COORD_N %zu\nstatic const int16_t PK_COORD[%zu][3] = {\n", n_coord, n_coord);
  for (i = 0; i < n_coord; i++)
    printf("{%d,%d,%d},%s", q(rot_stat_coords[i][0], "coord", (long)i), q(rot_stat_coords[i][1], "coord", (long)i),
           q(rot_stat_coords[i][2], "coord", (long)i), (i % 6 == 5) ? "\n" : "");
  printf("};\n");

  /* index: 5 small columns as int8; verify the offset column is the running
   * sum nc * (nheavy[type] + 1) so it can be recomputed (sentinel: 0) */
  printf("#define PK_IDX_N %zu\nstatic const int8_t PK_IDX[%zu][5] = {\n", n_idx, n_idx);
  for (i = 0; i < n_idx; i++) {
    int t = rot_stat_idx[i][0];
    for (k = 0; k < 5; k++) if (rot_stat_idx[i][k] < -128 || rot_stat_idx[i][k] > 127) { fprintf(stderr, "idx col %d out of int8\n", k); exit(1); }
    if (t >= 0) {
      if (rot_stat_idx[i][5] != off) { fprintf(stderr, "offset mismatch at row %zu: %d vs %ld\n", i, rot_stat_idx[i][5], off); exit(1); }
      off += (long)rot_stat_idx[i][4] * (nheavy[t] + 1);
    } else if (rot_stat_idx[i][5] != 0) { fprintf(stderr, "sentinel offset not 0\n"); exit(1); }
    printf("{%d,%d,%d,%d,%d},%s", rot_stat_idx[i][0], rot_stat_idx[i][1], rot_stat_idx[i][2], rot_stat_idx[i][3], rot_stat_idx[i][4], (i % 8 == 7) ? "\n" : "");
  }
  printf("};\n");
  fprintf(stderr, "packed: nco %zu, nco_pro %zu, coords %zu rows, idx %zu rows (coords end at %ld)\n", n_nco, n_pro, n_coord, n_idx, off);
  return 0;
}
