/*
 * PULCHRA's statistical tables, decoded at start-up from the packed form in
 * packed_tables.h (generated by tools/pack_tables.c from the original
 * nco_data.h / rot_data_coords.h / rot_data_idx.h).
 *
 * Storing the tables as int16 milli-Angstrom and int8 indices halves the
 * wasm binary.  Decoding v / 1000.0 in double and rounding to float yields
 * exactly the float the C compiler produced from the 3-decimal literal;
 * tools/verify_tables.c checks this bit for bit for every value.
 */
#include <stdlib.h>
#include <stdint.h>
#include "pulchra_common.h"
#include "packed_tables.h"

nco_struct *nco_stat = NULL;
nco_struct *nco_stat_pro = NULL;
float (*rot_stat_coords)[3] = NULL;
int (*rot_stat_idx)[6] = NULL;

static const int pk_nheavy[20] = {0, 1, 2, 2, 3, 3, 4, 3, 4, 4, 4, 4, 5, 5, 5, 7, 6, 7, 8, 10};

static nco_struct *unpack_nco(const int8_t (*bins)[3], const int16_t (*data)[24], size_t n) {
  nco_struct *out = (nco_struct *)malloc(sizeof(nco_struct) * n);
  size_t i; int j, k;
  for (i = 0; i < n; i++) {
    for (k = 0; k < 3; k++) out[i].bins[k] = bins[i][k];
    for (j = 0; j < 8; j++)
      for (k = 0; k < 3; k++) out[i].data[j][k] = (float)(data[i][3 * j + k] / 1000.0);
  }
  return out;
}

__attribute__((constructor)) static void pulchra_unpack_tables(void) {
  size_t i; int k; long off = 0;
  if (nco_stat) return;
  nco_stat = unpack_nco(PK_NCO_bins, PK_NCO_data, PK_NCO_N);
  nco_stat_pro = unpack_nco(PK_NCO_PRO_bins, PK_NCO_PRO_data, PK_NCO_PRO_N);

  rot_stat_coords = (float (*)[3])malloc(sizeof(float[3]) * PK_COORD_N);
  for (i = 0; i < PK_COORD_N; i++)
    for (k = 0; k < 3; k++) rot_stat_coords[i][k] = (float)(PK_COORD[i][k] / 1000.0);

  rot_stat_idx = (int (*)[6])malloc(sizeof(int[6]) * PK_IDX_N);
  for (i = 0; i < PK_IDX_N; i++) {
    int t = PK_IDX[i][0];
    for (k = 0; k < 5; k++) rot_stat_idx[i][k] = PK_IDX[i][k];
    rot_stat_idx[i][5] = t >= 0 ? (int)off : 0; /* running offset into rot_stat_coords; sentinel 0 */
    if (t >= 0) off += (long)PK_IDX[i][4] * (pk_nheavy[t] + 1);
  }
}
